set(PICO_IMU_SOURCES
    src/euler_angles.h
    src/imu.h
    src/imu.c
    src/main.c
    src/mpu9250_regs.h
    src/mpu9250.c
    src/mpu9250.h
    src/quaternion.c
    src/quaternion.h
    src/vector.h
)