set(PICO_IMU_SOURCES
    src/euler_angles.h
    src/IMU.h
    src/IMU.cpp
    src/main.cpp
    src/mpu9250_regs.h
    src/MPU9250.cpp
    src/MPU9250.h
    src/Quaternion.cpp
    src/Quaternion.h
    src/vector.h
)